### ISSUE TITLE
Add Provider to Terraform Registry

### ISSUE THREAD

**Issue by leighatami** [microsoft/terraform-provider-power-platform#145]
Add the power platform terraform provider to the terraform registry following these instructions https://developer.hashicorp.com/terraform/registry/providers/publishing

Note: Public Release Process including CELA approval need to be complete before this event per https://github.com/microsoft/terraform-provider-power-platform/issues/117
Also, repo needs to be made public in #176

**Comment by mattdot** [comment]
Started adding to registry but was blocked by an unrecognized GPG key.  Working with Hashicorp support team to resolve and get the provider fully published into the Terraform registry.

**Comment by mattdot** [comment]
Update: Still waiting for hashicorp support.  Easter holiday and support being in Europe has caused some delays in communication responsiveness.  I hope to get this resolved this week or find a way to escalate.

**Comment by leighatami** [comment]
closing as complete
