### ISSUE TITLE
D365 Finance Core System Configuration Represented in the Provider

### ISSUE THREAD

**Issue by ianjensenisme** [microsoft/terraform-provider-power-platform#151]
## Description

AS A user of the PPTP, I NEED to be able to specify and query the core configuration of my D365 Finance environments SO THAT I can track and avoid configuration drift.

### Resource

- Resource Name: powerplatform_D365FinanceConfiguration
- API documentation: Should cover most of the Org Admin setup at https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/organization-administration-home-page as well as some of the basic sys config in the System Administration module.
- Estimated complexity/effort: Hard, requires lots of functional knowledge and technical awareness of the underlying system data.
- Related resources/data sources: We will also need a datasource for querying.

### Potential Terraform Configuration

```hcl
# Sample Terraform config that describes how the new resource might look.

resource "example_resource" {
  name = "example"
  parameter1 = "value1"
  parameter2 = "value2"
}

```

## Definition of Done

- [ ] Data Transfer Objects (dtos)
- [ ] Data Client functions
- [ ] Resource Implementation
- [ ] Resource Added to Provider
- [ ] Unit Tests for Happy Path
- [ ] Unit Tests for error path
- [ ] Acceptance Tests
- [ ] Example in the /examples folder
- [ ] Schema Documentation in code
- [ ] Updated auto-generated provider docs with `make docs`

## Contributions

Do you plan to raise a PR to address this issue? YES?

See the [contributing guide](/CONTRIBUTING.md?) for more information about what's expected for contributions.

**Comment by mattdot** [comment]
@ianjensenisme please review this issue and let us know if it's still needed

**Comment by mattdot** [comment]
Closing this as not planned.
