### ISSUE TITLE
Application User Resource

### ISSUE THREAD

**Issue by leighatami** [microsoft/terraform-provider-power-platform#19]
As a TF user, I want to be able to create and manage application users

- [ ] Create new APP users
- [ ] Deactivate users, delete is not supported "At present, deleting an application user isn't supported.".
- [ ] Select App, "Add an app".
- [ ] Select Business unit / use default BU (existing business unit).
- [ ] Add / edit user security roles 

Doublecheck:
- [ ] Assign users to business units (this may be a user action in user resource).
- [ ] Remove user security roles (this may be a user action in user resource)

**Comment by eduardodfmex** [comment]
New Branch created and remove oldest ones.

**Comment by mattdot** [comment]
This is paused because we think we can implement this as a module once #45 is completed

**Comment by mattdot** [comment]
Closing this issue as not planned because we can implement application users using data_record resource
