### ISSUE TITLE
resource_environment may need updates to support D365 Finance environment version specification

### ISSUE THREAD

**Issue by ianjensenisme** [microsoft/terraform-provider-power-platform#317]
## Description

PPAC now supports version specs for D365 Finance environment deployments, so the provider should too. Here's the relevant announcement: https://www.yammer.com/dynamicsaxfeedbackprograms/#/threads/show?threadId=2826772202913792 .

### Resource

- Resource Name: resource_environment
- API documentation: [](https://www.yammer.com/dynamicsaxfeedbackprograms/#/threads/show?threadId=2826772202913792)
- Estimated complexity/effort: Should be easy, it's just a question of whether the template_metadata property gets a new field, or if a whole new property got added to the payload.
- Related resources/data sources: resource_environment, possibly datasource_environment.

### Potential Terraform Configuration

```hcl
resource "powerplatform_environment" "xpp-dev1" {
  display_name     = var.d365_finance_environment_name
  location         = var.location
  environment_type = var.environment_type
  templates = ["D365_FinOps_Finance"]
  template_metadata = "{\"PostProvisioningPackages\": [{ \"applicationUniqueName\": \"msdyn_FinanceAndOperationsProvisioningAppAnchor\",\n \"parameters\": \"DevToolsEnabled=true|DemoDataEnabled=true\"\n\"applicationVersion\": \"10.0.38.7\",\n }\n ]\n }"
  dataverse = {
    language_code     = var.language_code
    currency_code     = var.currency_code
    security_group_id = "00000000-0000-0000-0000-000000000000"
  }
}

```

## Definition of Done

- [ ] Data Transfer Objects (dtos)
- [ ] Data Client functions
- [ ] Resource Implementation
- [ ] Resource Added to Provider
- [ ] Unit Tests for Happy Path
- [ ] Unit Tests for error path
- [ ] Acceptance Tests
- [ ] Example in the /examples folder
- [ ] Schema Documentation in code
- [ ] Updated auto-generated provider docs with `make docs`

## Contributions

Do you plan to raise a PR to address this issue? YES

**Comment by mattdot** [comment]
@ianjensenisme isn't this just passing different json to an existing resource?  Does the resource actually need to change to support this?

**Comment by mattdot** [comment]
Closing this issue since we don't validate the template_metadata json and you can just specify the version.  If you think it's important to document, consider opening an issue on the quickstarts repo with an example of how to deploy D365 Finance with a version.
