### ISSUE TITLE
Add Data Source examples for powerplatform_security_roles and powerplatform_data_loss_prevention_policies

### ISSUE THREAD

**Issue by eduardodfmex** [microsoft/terraform-provider-power-platform#322]
## Add Data Source examples for powerplatform_security_roles and powerplatform_data_loss_prevention_policies

We need to create documentation examples for 

- powerplatform_security_roles [powerplatform_security_roles](https://registry.terraform.io/providers/microsoft/power-platform/latest/docs/data-sources/security_roles)

- powerplatform_data_loss_prevention_policies [powerplatform_data_loss_prevention_policies](https://registry.terraform.io/providers/microsoft/power-platform/latest/docs/data-sources/data_loss_prevention_policies)

## Definition of Done

- [ ] Users should be able to use the documentation to complete a task

## Contributions

Do you plan to raise a PR to address this issue? YES / NO?

See the [contributing guide](/CONTRIBUTING.md?) for more information about what's expected for contributions.

**Comment by mawasile** [comment]
@eduardodfmex i've added an example for dlp policies, but security roles already has one
