### ISSUE TITLE
Improve documentation of import functionality

### ISSUE THREAD

**Issue by MarvinBangert** [microsoft/terraform-provider-power-platform#394]
## Description

It would be great to have an "Import" function within the resources, like it is within azurerm functions to import existing infrastructure like environments using Environment ID or DLP.
Example from [azurerm_application_gateway](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#import)

### Resource

- Resource Name: terraform import powerplatform_environment.example
- API documentation: 
- Estimated complexity/effort: 
- Related resources/data sources: 

### Potential Terraform Configuration

```hcl
# Sample Terraform config that describes how the new resource might look.

terraform import powerplatform_environment.example
terraform import powerplatform_data_loss_prevention_policy.example

```

## Definition of Done

- [ ] Data Transfer Objects (dtos)
- [ ] Data Client functions
- [ ] Resource Implementation
- [ ] Resource Added to Provider
- [ ] Unit Tests for Happy Path
- [ ] Unit Tests for error path
- [ ] Acceptance Tests
- [ ] Example in the /examples folder
- [ ] Schema Documentation in code
- [ ] Updated auto-generated provider docs with `make docs`

## Contributions

Do you plan to raise a PR to address this issue? NO

See the [contributing guide](/CONTRIBUTING.md?) for more information about what's expected for contributions.

**Comment by rpothin** [comment]
Hi @MarvinBangert,

I hope you are doing well.

If I am not wrong - I will let the maintainers correct me if it is the case - you can already achieve this 😊
It is something I included in a [GitHub workflow](https://github.com/rpothin/PowerPlatform-Governance-With-Terraform/blob/f376988ba4f53a8ee1a71b725363a769d8f7170c/.github/workflows/terraform-import.yaml#L108C7-L110C152) and you can see the behavior with a previous [run](https://github.com/rpothin/PowerPlatform-Governance-With-Terraform/actions/runs/9967450693/job/27541153635).

Have a great weekend.
Regards,
Raphael

**Comment by MarvinBangert** [comment]
Hi @rpothin,
thanks for your quick reply! I will check this out, didn't found anything in the Terraform docs, so I thought it's not implemented yet.

Have a great start into the week!
BR
Marvin

**Comment by mattdot** [comment]
Repurposing this to be a documentation task since this functionality should be already available on the resources.
