### ISSUE TITLE
solution validation failed: need requirements documented

### ISSUE THREAD

**Issue by webstean** [microsoft/terraform-provider-power-platform#409]
## Description

We need documentation to explain the requirements for the naming of ZIP files with the "powerplatform_solution" resource.

Currently the provides produce terse errors, and documentation is silent.

solution validation failed: Unexpected : Specified argument was out of the range of valid values.
Parameter name: zipFileName
solution failed with status: 'Failed'

## Definition of Done

- [ X] We should have clear guidance on the requirements for the "solution_file" and "solution_name" options in the  "powerplatform_solution" resource.

## Contributions

Do you plan to raise a PR to address this issue? NO

See the [contributing guide](/CONTRIBUTING.md?) for more information about what's expected for contributions.

**Comment by mattdot** [comment]
Agree we can do better here. Will add documentation in an upcoming release.

**Comment by webstean** [comment]
Do you even need the  solution_name  parameter?
The GUI seems to take the ZIP file and work out what the name is, can you do that?

**Comment by mattdot** [comment]
Will look into that.  A heuristic from the solution file name would be pretty brittle and restrictive on that parameter, but maybe we can read it from zip file contents.  Will investigate if we can make solution name optional to allow for overriding the default value

**Comment by mawasile** [comment]
We needed the unique name to find the solution just after the async import process finished and we don't know the solutionid yet. I am working on a change to remove solution_name attribute completely, but this will be a breaking change for the resource. 
I will try to get that in the next release.
