### ISSUE TITLE
Mismatch on resource and data naming between the index and the actual resource/data entry in Terraform Registry

### ISSUE THREAD

**Issue by webstean** [microsoft/terraform-provider-power-platform#410]
## Description

The Terraform registry index, includes a "-", example power-platform_billing_policy, whilst the actual resource is called powerplatform_billing_policy, not the exact "-" between power and platform.

![image](https://github.com/user-attachments/assets/fae51ab7-1363-402d-bb3a-648af8019e47)

## Definition of Done

- [X] Resolve inconsistency.
- 
## Contributions

Do you plan to raise a PR to address this issue? NO

See the [contributing guide](/CONTRIBUTING.md?) for more information about what's expected for contributions.

**Comment by mawasile** [comment]
Hi @webstean 

Thanks for pointing out. This issue is on Hashicrop side and how they generate docs on registry website. We are working with them to get that fixed without the need to republish the provider.
