### ISSUE TITLE
powerplatform_environment (Resource) should support the refresh cadence, administration mode, and description parameters

### ISSUE THREAD

**Issue by webstean** [microsoft/terraform-provider-power-platform#417]
## Description

Currently the powerplatform_environment (Resource) does not support neither the refresh cadence and description parameters. Both of which are supported in the Power Apps admin centre.

### Resource

- Resource Name: powerplatform_powerplatform_environmen
- API documentation: 
- Estimated complexity/effort: Easy - should be just adding the applicable parameters.
- Related resources/data sources: Nil.

### Potential Terraform Configuration

```hcl
resource "powerplatform_environment" "development" {
  display_name     = "example_environment"
  description = "example description - to be added"
  cadence = "Frequent" ## or "Moderate"
  administration_mode = "enabled" ## or "disabled"
  location         = "europe"
  azure_region     = "northeurope"
  environment_type = "Sandbox"
}
```

## Definition of Done

- [ ] Data Transfer Objects (dtos)
- [ ] Data Client functions
- [X ] Resource Updated
- [X ] Unit Tests for Happy Path
- [X ] Unit Tests for error path
- [X ] Acceptance Tests
- [X ] Example updated in the /examples folder
- [X ] Schema Documentation in code
- [X ] Updated auto-generated provider docs with `make docs`

## Contributions

Do you plan to raise a PR to address this issue? YES / NO?

See the [contributing guide](/CONTRIBUTING.md?) for more information about what's expected for contributions.

**Comment by mawasile** [comment]
Thanks, let me look into that

**Comment by mattdot** [comment]
@mawasile also add `environment_group`

**Comment by webstean** [comment]
> @mawasile also add `environment_group`

Was going to add that as an issue, once the environment_group functionality is released. :-)
