### ISSUE TITLE
Soften the experimental warning for the repo in the 3.0 release

### ISSUE THREAD

**Issue by mattdot** [microsoft/terraform-provider-power-platform#420]
## Description

Make the experimental warning softer and allow for some use in production (at users own risk).

## Definition of Done

- [ ] Users should be able to use the documentation to complete a task

## Contributions

Do you plan to raise a PR to address this issue? YES

See the [contributing guide](/CONTRIBUTING.md?) for more information about what's expected for contributions.

**Comment by webstean** [comment]
Is there an estimate/guesstimate as to when the provider will be GA?
