### ISSUE TITLE
Add the ability powerplatform_environment_application_package_install (resource) to install, upgrade and delete of solutions from url/appsource

### ISSUE THREAD

**Issue by webstean** [microsoft/terraform-provider-power-platform#429]
## Description

Allow solution installation from [Microsoft ApppSource](https://appsource.microsoft.com/en-us/) and ideally from any URL for the maximum flexibility.

### Resource

- Resource Name: powerplatform_[powerplatform_solution]
- API documentation: n/a
- Estimated complexity/effort: easy
- Related resources/data sources: data.powerplatform_solutions, add outputs.

### Potential Terraform Configuration

```hcl
resource "powerplatform_solution" "example" {
  environment_id = powerplatform_environment.example.id
  solution_file  = "${path.module}/${var.solution_name}_Complex_1_1_0_0.zip"
or
  solution_appsource = "Creator Kit"
  solution_appsource_publisher = "Microsoft Corp - Power CAT"
or
  solution_url = "https://cnn.com/solution.zip"

  settings_file  = local_file.solution_settings_file.filename
}
```

## Definition of Done

- [ ] Data Transfer Objects (dtos)
- [ ] Data Client functions
- [ ] Resource Implementation
- [ ] Resource Added to Provider
- [ ] Unit Tests for Happy Path
- [ ] Unit Tests for error path
- [ ] Acceptance Tests
- [ ] Example in the /examples folder
- [ ] Schema Documentation in code
- [ ] Updated auto-generated provider docs with `make docs`

## Contributions

Do you plan to raise a PR to address this issue? NO

See the [contributing guide](/CONTRIBUTING.md?) for more information about what's expected for contributions.

**Comment by mattdot** [comment]
For solution_url, unless the API explicitly supports loading a solution from url, I think the "terraform" way to do this would be to use a local provisioner to download the file and then just use solution_file

```terraform
resource "null_resource" "solution_zip" {

  provisioner "local-exec" {
    command = "curl -o solution.zip https://example.com/solution.zip"
  }

  provisioner "local-exec" {
    when    = destroy
    command = "rm solution.zip"
  }
}
```

will get back to you on app source

**Comment by mattdot** [comment]
Looks like appsource uses a different API `
https://api.admin.powerplatform.microsoft.com/api/AppManagement/AddTenantAppSourceRequest?geoType=Na`.  We will discuss.

**Comment by mawasile** [comment]
We do support appsource as a separate resource:
https://github.com/microsoft/terraform-provider-power-platform/blob/main/examples/resources/powerplatform_environment_application_packages/resource.tf

**Comment by webstean** [comment]
This resource's documentation does not include any mention of appsource and talks about the "Dynamics 365 applications" which is very legacy commentary. So that probably needs to be modernised / updated.

powerplatform_environment_application_package_install (Resource) includes the statement: -

This resource does not support updating or deleting applications. The expected behavior is that the application is installed and remains installed until the environment is deleted.

So that is extremely limiting, and I don't see how the provider can go to GA, with these sort of limitations, it should support both deleting / upgrading existing solutions/applications.

**Comment by webstean** [comment]
Changed this issue, to be about improving: **_powerplatform_environment_application_package_instal_** (resource)

**Comment by mattdot** [comment]
Yeah, that resource is not for AppSource.  We don't have a way to install from appsource right now.  

That resource covers what the current documentation and admin center UI calls Dynamics 365 apps

https://learn.microsoft.com/en-us/power-platform/admin/manage-apps

The terminology Power Platform itself uses is very confusing in this space since you have solutions, app packages, d365 tenant apps, d365 environment apps, app source, etc.  As much as possible we want to be consistent with how admin center or the underlying API refers to features to avoid confusion.  But there's clearly some confusion here.  I like how you're thinking about the space.  I don't know if/how we can unify all these concepts into one resource.  Willing to keep exploring though.

**Comment by webstean** [comment]
Thanks for the clarification and guidance, I've updated my issues appropriately.

**Comment by webstean** [comment]
> For solution_url, unless the API explicitly supports loading a solution from url, I think the "terraform" way to do this would be to use a local provisioner to download the file and then just use solution_file
> 
> ```hcl
> resource "null_resource" "solution_zip" {
> 
>   provisioner "local-exec" {
>     command = "curl -o solution.zip https://example.com/solution.zip"
>   }
> 
>   provisioner "local-exec" {
>     when    = destroy
>     command = "rm solution.zip"
>   }
> }
> ```
@mattdot
Yes, you could do that, but the goal of a provider should be hide the details of the underlying API from the terraform developer. I would imagine it would be a requirement to install a solution ZIP file from a Storage Blob (which could just be a URL) and the provider should support that directly, regardless of if the underlying API supports it or not. IMHO.

**Comment by mattdot** [comment]
We did some research on this.  App Source, Catalog, and D365 apps are all installed as "application packages" which may not be a single solution. Could be 0 to many.  Therefore it doesn't make sense to combine these with the solution resource.
