### ISSUE TITLE
Need ability to retrieve organization (unique) name

### ISSUE THREAD

**Issue by webstean** [microsoft/terraform-provider-power-platform#471]
## Description

Enhancement to: `data.powerplatform_environments` and `resource.powerplatform_environment`
Need ability to retrieve details of the tenancy, for example the xrmtoolkit needs the organization name and domain for its connection string.

### Resource

- Resource Name: `powerplatform_environment` & `powerplatform_environments`
- API documentation:  [organizationdatasyncsubscriptionentity ](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/organizationdatasyncsubscriptionentity?view=dataverse-latest)
- Estimated complexity/effort:  moderate
- Related resources/data sources: 
- 
### Potential Terraform Configuration

```hcl
# Sample Terraform config that describes how the new resource might look.

data "powerplatform_environments" "example" {
}

Returns:
name:
domainname:

```

## Definition of Done

- [ ] Data Transfer Objects (dtos)
- [ ] Data Client functions
- [ ] Resource Implementation
- [ ] Resource Added to Provider
- [ ] Unit Tests for Happy Path
- [ ] Unit Tests for error path
- [ ] Acceptance Tests
- [ ] Example in the /examples folder
- [ ] Schema Documentation in code
- [ ] Updated auto-generated provider docs with `make docs`

## Contributions

Do you plan to raise a PR to address this issue? NO

See the [contributing guide](/CONTRIBUTING.md?) for more information about what's expected for contributions.

**Comment by webstean** [comment]
To do this via the GUI:
In the Power Platform admin center, select an environment. Select Settings > Resources > All legacy settings.

For [Unified Interface](https://learn.microsoft.com/en-us/power-platform/admin/about-unified-interface), in the upper-right corner select Settings (Gear button.) > Advanced Settings.

Go to Settings > Customizations > Developer Resources.

Under Instance Reference Information, make note of ID and Unique Name. **Unique Name is the organization name.**

**Comment by mattdot** [comment]
Making some edits to this issue because this is about `powerplatform_environment` and not `powerplatform_tenant`
