### ISSUE TITLE
Module referenced in example

### ISSUE THREAD

**Issue by mdlister** [microsoft/terraform-provider-power-platform#507]
## Description

The power-platform_data_resource appears to have an error in the example. https://registry.terraform.io/providers/microsoft/power-platform/latest/docs/resources/data_record 

It references a module in the code but I can't see it declared anywhere or how to use it. 

`module "business_unit" {
  source                  = "./res_business_unit"
  environment_id          = powerplatform_environment.data_record_example_env.id
  name                    = "my business unit"
  costcenter              = "123"
  parent_business_unit_id = one(data.powerplatform_data_records.root_business_unit.rows).businessunitid
}`

## Definition of Done

- [ ] Users should be able to use the documentation to complete a task

## Contributions

NO, I'm not sure how to fix it myself. 

See the [contributing guide](/CONTRIBUTING.md?) for more information about what's expected for contributions.

**Comment by mawasile** [comment]
Hi @mdlister the code is in the examples folder, the terraform registry does only display the main.tf file of each example for the repository.

https://github.com/microsoft/terraform-provider-power-platform/tree/main/examples/resources/powerplatform_data_record

**Comment by mattdot** [comment]
There is some unreleased documentation improvements for business units, etc.  You can look on main branch to see now, but terraform documentation site will be updated next time we release.
